package com.haulmont.yarg.reporting;


import java.io.OutputStream;

/**
 * This class is entry point for reporting functionality
 * Use it to print reports
 */
public interface ReportingAPI {

    /**
     * This method generates report and put result to output stream.
     * ! Attention : ReportOutputDocument.content field is null in this case !
     *
     * @param runParams - parameters for report printing
     * @param outputStream - the stream which accept binary file generated by reporting
     * @return ReportOutputDocument - object which describes generated report - its name, type etc
     */
    ReportOutputDocument runReport(RunParams runParams, OutputStream outputStream);

    /**
     * This method generates report and put result to ReportOutputDocument.content field
     * @param runParams - parameters for report printing
     * @return ReportOutputDocument - object which describes generated report - its name, type etc
     */
    ReportOutputDocument runReport(RunParams runParams);
}
